// Generated by gencpp from file davinci_msg/Force.msg
// DO NOT EDIT!


#ifndef DAVINCI_MSG_MESSAGE_FORCE_H
#define DAVINCI_MSG_MESSAGE_FORCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace davinci_msg
{
template <class ContainerAllocator>
struct Force_
{
  typedef Force_<ContainerAllocator> Type;

  Force_()
    : force_x(0.0)
    , force_y(0.0)
    , force_z(0.0)  {
    }
  Force_(const ContainerAllocator& _alloc)
    : force_x(0.0)
    , force_y(0.0)
    , force_z(0.0)  {
  (void)_alloc;
    }



   typedef double _force_x_type;
  _force_x_type force_x;

   typedef double _force_y_type;
  _force_y_type force_y;

   typedef double _force_z_type;
  _force_z_type force_z;





  typedef boost::shared_ptr< ::davinci_msg::Force_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::davinci_msg::Force_<ContainerAllocator> const> ConstPtr;

}; // struct Force_

typedef ::davinci_msg::Force_<std::allocator<void> > Force;

typedef boost::shared_ptr< ::davinci_msg::Force > ForcePtr;
typedef boost::shared_ptr< ::davinci_msg::Force const> ForceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::davinci_msg::Force_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::davinci_msg::Force_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace davinci_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'davinci_msg': ['/home/zzz/force_reflection/src/force_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::davinci_msg::Force_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::davinci_msg::Force_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::davinci_msg::Force_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::davinci_msg::Force_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::davinci_msg::Force_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::davinci_msg::Force_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::davinci_msg::Force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3834bb22b09698ded602f23cb069ae6";
  }

  static const char* value(const ::davinci_msg::Force_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3834bb22b09698dULL;
  static const uint64_t static_value2 = 0xed602f23cb069ae6ULL;
};

template<class ContainerAllocator>
struct DataType< ::davinci_msg::Force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "davinci_msg/Force";
  }

  static const char* value(const ::davinci_msg::Force_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::davinci_msg::Force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 force_x\n\
float64 force_y\n\
float64 force_z\n\
\n\
";
  }

  static const char* value(const ::davinci_msg::Force_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::davinci_msg::Force_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.force_x);
      stream.next(m.force_y);
      stream.next(m.force_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Force_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::davinci_msg::Force_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::davinci_msg::Force_<ContainerAllocator>& v)
  {
    s << indent << "force_x: ";
    Printer<double>::stream(s, indent + "  ", v.force_x);
    s << indent << "force_y: ";
    Printer<double>::stream(s, indent + "  ", v.force_y);
    s << indent << "force_z: ";
    Printer<double>::stream(s, indent + "  ", v.force_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DAVINCI_MSG_MESSAGE_FORCE_H
